import AuthenticationServices

typealias PresentationContext = ASAuthorizationControllerPresentationContextProviding
typealias PublicKeyCredentialRegistration = ASAuthorizationPlatformPublicKeyCredentialRegistration
