import AuthenticationServices

typealias PresentationContext = ASAuthorizationControllerPresentationContextProviding
typealias PublicKeyCredentialRegistration = ASAuthorizationPlatformPublicKeyCredentialRegistration
typealias PublicKeyCredentialAssertion = ASAuthorizationPlatformPublicKeyCredentialAssertion
